# Generated by Django 2.0.7 on 2019-01-28 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Connectivities',
            },
        ),
        migrations.CreateModel(
            name='Power_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('switch', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=12)),
                ('time_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='connectivity',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargerApp.Power_source'),
        ),
    ]
